describe('Fulfill Testing of Bucket 2 Project', function() {
  it('.should pass all tests', function () {
    cy.visit('../index.html')
    cy.get('#splash > div > h1').should('have.innertext', "Burke Weather!")
    cy.get('.job-form > input').as('inputs')
    cy.get('@inputs').should('have.text', "")
    cy.get('@inputs').eq(0).as('jobTitle')
    cy.get('@inputs').eq(1).as('pay')
    cy.get('@inputs').eq(2).as('submitButton')
    cy.get('@jobTitle').type('Job Title')
    cy.get('@pay').type('Pay')
    cy.get('.job-form > textarea').type('Description')
    cy.get('@submitButton').click()
    cy.get('@inputs').should('have.text', "")
    cy.get('#job-listings > li > small').as('smallTag')
    cy.get('#job-listings > li > h4').contains('Title').should('have.text','Job Title')
    cy.get('@smallTag').eq(0).contains('Pay').should('have.text','Pay')
    cy.get('#job-listings > li > p').contains('Description').should('have.text','Description')
    cy.get('@smallTag').eq(1).should('have.text','0 dinos are interested in this job')
  })
})
